component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/hibernate/.*
- ./bin/org/hibernate/dialect/.*
- ./bin/org/hsqldb/.*
- ./bin/org/hsqldb/cmdline/.*
- ./bin/org/hsqldb/cmdline/sqltool/.*
- ./bin/org/hsqldb/dbinfo/.*
- ./bin/org/hsqldb/error/.*
- ./bin/org/hsqldb/index/.*
- ./bin/org/hsqldb/jdbc/.*
- ./bin/org/hsqldb/jdbc/pool/.*
- ./bin/org/hsqldb/lib/.*
- ./bin/org/hsqldb/lib/java/.*
- ./bin/org/hsqldb/lib/tar/.*
- ./bin/org/hsqldb/lib/tar/rb/.*
- ./bin/org/hsqldb/navigator/.*
- ./bin/org/hsqldb/persist/.*
- ./bin/org/hsqldb/result/.*
- ./bin/org/hsqldb/rights/.*
- ./bin/org/hsqldb/rowio/.*
- ./bin/org/hsqldb/sample/.*
- ./bin/org/hsqldb/scriptio/.*
- ./bin/org/hsqldb/server/.*
- ./bin/org/hsqldb/store/.*
- ./bin/org/hsqldb/test/.*
- ./bin/org/hsqldb/types/.*
- ./bin/org/hsqldb/util/.*
- ./bin/org/hsqldb/util/preprocessor/.*
- ./hsqldb/.*
- ./hsqldb/bin/.*
- ./hsqldb/build/.*
- ./hsqldb/doc/.*
- ./hsqldb/doc/apidocs/.*
- ./hsqldb/doc/apidocs/org/.*
- ./hsqldb/doc/apidocs/org/hsqldb/.*
- ./hsqldb/doc/apidocs/org/hsqldb/class-use/.*
- ./hsqldb/doc/apidocs/org/hsqldb/cmdline/.*
- ./hsqldb/doc/apidocs/org/hsqldb/cmdline/class-use/.*
- ./hsqldb/doc/apidocs/org/hsqldb/jdbc/.*
- ./hsqldb/doc/apidocs/org/hsqldb/jdbc/class-use/.*
- ./hsqldb/doc/apidocs/org/hsqldb/lib/.*
- ./hsqldb/doc/apidocs/org/hsqldb/lib/class-use/.*
- ./hsqldb/doc/apidocs/org/hsqldb/lib/tar/.*
- ./hsqldb/doc/apidocs/org/hsqldb/lib/tar/class-use/.*
- ./hsqldb/doc/apidocs/org/hsqldb/sample/.*
- ./hsqldb/doc/apidocs/org/hsqldb/sample/class-use/.*
- ./hsqldb/doc/apidocs/org/hsqldb/server/.*
- ./hsqldb/doc/apidocs/org/hsqldb/server/class-use/.*
- ./hsqldb/doc/apidocs/org/hsqldb/util/.*
- ./hsqldb/doc/apidocs/org/hsqldb/util/class-use/.*
- ./hsqldb/doc/bin/.*
- ./hsqldb/doc/bin/org/.*
- ./hsqldb/doc/bin/org/hsqldb/.*
- ./hsqldb/doc/bin/org/hsqldb/sample/.*
- ./hsqldb/doc/bin/org/hsqldb/server/.*
- ./hsqldb/doc/bin/org/hsqldb/test/.*
- ./hsqldb/doc/guide/.*
- ./hsqldb/doc/images/.*
- ./hsqldb/doc/images/db/.*
- ./hsqldb/doc/images/db/callouts/.*
- ./hsqldb/doc/lib/.*
- ./hsqldb/doc/util-guide/.*
- ./hsqldb/doc/verbatim/.*
- ./hsqldb/doc/verbatim/sample/.*
- ./hsqldb/doc/verbatim/testrun/.*
- ./hsqldb/doc/verbatim/testrun/sqltool/.*
- ./hsqldb/lib/.*
- ./hsqldb/sample/.*
- ./hsqldb/stylesheets/.*
- ./hsqldb/testrun/.*
- ./hsqldb/testrun/hsqldb/.*
- ./hsqldb/testrun/hsqlodbc/.*
- ./hsqldb/testrun/sqltool/.*
- ./lib/.*
